/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import dados.ConexaoDB;
import dados.UsuarioDAO;
import helpers.ValidarForm;
import java.sql.Date;
import java.text.ParseException;
import static javax.swing.JOptionPane.*;
import javax.swing.UIManager;
import modelos.Usuario;

/**
 *
 * @author danie
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form A3
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo_Cad = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        lblNasc = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConf = new javax.swing.JLabel();
        btnCadastrar_Cad = new javax.swing.JButton();
        btnCancelar_Cad = new javax.swing.JButton();
        btnExcluir_Cad = new javax.swing.JButton();
        txtID_Cad = new javax.swing.JTextField();
        txtNome_Cad = new javax.swing.JTextField();
        txtEmail_Cad = new javax.swing.JTextField();
        pswSenha_Cad = new javax.swing.JPasswordField();
        pswConf_Cad = new javax.swing.JPasswordField();
        txtDataNasc_Cad = new javax.swing.JFormattedTextField();
        txtCelular_Cad = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo_Cad.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo_Cad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo_Cad.setText("FlowBank");

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setText("ID");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Nome");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("E-mail");

        lblCel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCel.setText("Celular");

        lblNasc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNasc.setText("Data Nasc.");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenha.setText("Senha");

        lblConf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblConf.setText("Conf. Senha");

        btnCadastrar_Cad.setText("Cadastrar");
        btnCadastrar_Cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar_CadActionPerformed(evt);
            }
        });

        btnCancelar_Cad.setText("Cancelar");

        btnExcluir_Cad.setText("Excluir");
        btnExcluir_Cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir_CadActionPerformed(evt);
            }
        });

        txtID_Cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_CadActionPerformed(evt);
            }
        });

        pswConf_Cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswConf_CadActionPerformed(evt);
            }
        });

        try {
            txtDataNasc_Cad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNasc_Cad.setToolTipText("No formato dd/mm/yyyy");
        txtDataNasc_Cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNasc_CadActionPerformed(evt);
            }
        });

        try {
            txtCelular_Cad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular_Cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelular_CadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(btnCadastrar_Cad)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar_Cad)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir_Cad)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConf)
                    .addComponent(lblSenha)
                    .addComponent(lblNasc)
                    .addComponent(lblCel)
                    .addComponent(lblEmail)
                    .addComponent(lblNome)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID_Cad)
                    .addComponent(txtNome_Cad)
                    .addComponent(txtEmail_Cad)
                    .addComponent(pswSenha_Cad)
                    .addComponent(pswConf_Cad, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtDataNasc_Cad)
                    .addComponent(txtCelular_Cad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblTitulo_Cad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addComponent(txtID_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCel)
                    .addComponent(txtCelular_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNasc)
                    .addComponent(txtDataNasc_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(pswSenha_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConf)
                    .addComponent(pswConf_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar_Cad)
                    .addComponent(btnCancelar_Cad)
                    .addComponent(btnExcluir_Cad))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrar_CadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar_CadActionPerformed
        String nome = txtNome_Cad.getText();
        String email = txtEmail_Cad.getText();
        String celular = txtCelular_Cad.getText();
        String nasc = txtDataNasc_Cad.getText();
        String senha= pswSenha_Cad.getText();
        String conf= pswConf_Cad.getText();
        
        String[] campos = new String[]{
            nome, email, celular, nasc, senha, conf
        };
 
        boolean preenchido = ValidarForm.camposPreenchidos(campos);
        if(preenchido==false){
            showMessageDialog(null,"Todos os campos devem estar preenhidos!","Informações Incompletas",WARNING_MESSAGE);
            return;
        }
        System.out.println(nasc);
        Date dataFormatada;
        
        try {
            dataFormatada = ValidarForm.formatarData(nasc);
        } catch (ParseException e){
            showMessageDialog(null, "Ocorreu algum erro. Tente novamente mais tarde.", "", WARNING_MESSAGE);
            System.out.println(e);
            return;
        }
        
        if(!senha.equals(conf)){
            showMessageDialog(null,"As senhas devem ser iguais!","Erro",ERROR_MESSAGE);
            return;
        }
        
        showMessageDialog(null, "Tudo OK para insertar no banco de dados");
        Usuario u = new Usuario();
        u.setNome(nome);
        u.setEmail(email);
        u.setCelular(celular);
        u.setNascimento(dataFormatada);
        UsuarioDAO uDao = new UsuarioDAO();
        
        uDao.criarUsuario(u);
    }//GEN-LAST:event_btnCadastrar_CadActionPerformed

    private void btnExcluir_CadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir_CadActionPerformed
        // TODO add your handling code here:
        UIManager.put("OptionPane.cancelButtonText","Cancelar");
        UIManager.put("OptionPane.okButtonText","Excluir");
        int confExclui = showConfirmDialog(null,"Você tem certeza?","Excluir Cadastro", WARNING_MESSAGE);
        //excluir cadastro do banco de dados
        if(confExclui==0){
            dispose();
        }
    }//GEN-LAST:event_btnExcluir_CadActionPerformed

    private void txtID_CadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_CadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_CadActionPerformed

    private void pswConf_CadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswConf_CadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswConf_CadActionPerformed

    private void txtDataNasc_CadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNasc_CadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNasc_CadActionPerformed

    private void txtCelular_CadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelular_CadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelular_CadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar_Cad;
    private javax.swing.JButton btnCancelar_Cad;
    private javax.swing.JButton btnExcluir_Cad;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblConf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNasc;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo_Cad;
    private javax.swing.JPasswordField pswConf_Cad;
    private javax.swing.JPasswordField pswSenha_Cad;
    private javax.swing.JFormattedTextField txtCelular_Cad;
    private javax.swing.JFormattedTextField txtDataNasc_Cad;
    private javax.swing.JTextField txtEmail_Cad;
    private javax.swing.JTextField txtID_Cad;
    private javax.swing.JTextField txtNome_Cad;
    // End of variables declaration//GEN-END:variables
}
